### DISCUSSION TITLE
RaspberryMatic mit Home Assistant verbinden

### DISCUSSION THREAD

**Discussion by kaelsaes** [OpenCCU/OpenCCU#1630] [🇩🇪 Fragen&Antworten] [answered]
Moin Jens,

zunächst mal vielen Dank für Deine tolle Arbeit.

Ich nutze die RaspberryMatic schon seit Jahren mit FHEM. Beides läuft auf separaten Raspberry PIs.

Nun interessiere ich mich für Home Assistant und habe dazu einen ersten RPI4 aufgesetzt.

Dass ich RaspberryMatic als Add On in Home Assistant installieren kann, habe ich gefunden.
Ich würde aber gerne RaspberryMatic weiterhin auf einem eigenen RPI laufen lassen und Home Assistant mit RaspberryMatic verbinden.
Funktioniert das und gibt es dazu eine Anleitung?

Vielen Dank für Deine Unterstützung.

Grüße Kai

**Comment by sqoerk-dev** [comment, marked as answer]
Hallo,

Das habe ich genau so seit 2 Jahren laufen. Anleitung ist diese hier: https://www.home-assistant.io/integrations/homematic

Geht also nur direkt in der Konfigurationsdatei.

Mfg

**Reply by kaelsaes** [reply]
Vielen Dank für Deine schnelle Rückmeldung.

Dann schaue ich mir das mal genauer an.

Grüße

**Reply by kaelsaes** [reply]
Hallo zusammen,

ich habe jetzt meine configuration.yaml entsprechend erweitert und nach einem Neustart sind alle Geräte der RaspberryMatic in Home Assistant angelegt.
Allerdings werden nur Entitäten und keine Geräte angelegt.

In Automatisierungen kann ich nur Geräte und keine Entitäten schalten/steuern.

Ist das richtig so und wie kann ich jetzt trotzdem z.B. einen Homematic Schaltaktor per Automatisierung schalten?

Vielen Dank.

Grüße

**Reply by sqoerk-dev** [reply]
Guten Abend, 

das habe ich noch nie Probiert, da ich hier nur Heizungssteuerung betreibe, außer ein SmartLock.

Dafür habe ich noch folgendes in die Konfig hinzugefügt, vlt. kann man das ja adaptieren?

```
lock:
### Homematic IP DLD door lock template
- platform: template
  name: Hoftür
  unique_id: basedoor
  value_template: "{{ state_attr('homematic.ccu2', 'hoftuer_lock_status') }}"
  lock:
    service: homematic.set_device_value
    data:
      address: "002A1BE9A78xxx"
      channel: 1
      param: LOCK_TARGET_LEVEL
      value: 0
  unlock:
    service: homematic.set_device_value
    data:
      address: "002A1BE9A78xxx"
      channel: 1
      param: LOCK_TARGET_LEVEL
      value: 1
```
