### DISCUSSION TITLE
Raspberrymatic in Docker on Odroid C2 - Starting multimacd: ..........ERROR

### DISCUSSION THREAD

**Discussion by Ro4cHii** [OpenCCU/OpenCCU#2079] [🇩🇪 Fragen&Antworten]
Hallo,

ich habe hier schon mal vor einer Weile nach Hilfe gefragt, hatte das Vorhaben aber erstmal wieder in den Hintergrund gestellt.

Letzte Woche habe ich mich erneut herangewagt, Raspberrymatic auf meinem Odroid C2 im Docker Container laufen zu lassen.

**docker-compose.yaml**
```
version: "3.8"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: homematic-raspi
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /docker/ccu_data:/usr/local:rw
      - /lib/modules:/lib/modules:ro
      - /run/udev/control:/run/udev/control
    ports:
      - "8080:80"
      - "2001:2001"
      - "2010:2010"
      - "9292:9292"
      - "8181:8181"
volumes:
  ccu_data:
```

Der Container wird erfolgreich deployed, allerdings werden mir in der Weboberfläche keine Geräte angezeigt.
Das HM-MOD-RPI-PCB scheint allerdings prinzipiell erkannt zu werden, wie die nachfolgenden Logs zeigen:

```
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.18.0.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/GPIO@c11084c0.serial, HmIP: HM-MOD-RPI-PCB/GPIO@c11084c0.serial, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
**Starting multimacd: ..........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing**
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.11.20221005 (raspmatic_oci_arm64)
```

Irgendeine Idee, was hier noch fehlt?

Viele Grüße
Ro4cHii
