### DISCUSSION TITLE
IPWired Komponenten nicht über HA steuerbar?!

### DISCUSSION THREAD

**Discussion by ntdsutil** [OpenCCU/OpenCCU#2246] [🇩🇪 Fragen&Antworten] [answered]
Mahlzeit zusammen,

habe HA und RaspberryMatic in separaten VMs laufen. Beides funzt und auch die Integration (HMIP local) lief sauber durch. Ich sehe ALLE Komponenten. 
Nun zum Problem: Will ich eine Aktion auf einem der Wired Komponenten triggern, bspw. Licht an dann passiert nichts. Ich verwende als Aktor auch Wired Komponenten. Triggere ich meine Aktion aus der UI, also ohne den Tastendruck, dann geht das Licht an.

Nun zu meinen Fragen: Im YAML sehe ich als Interface das RF-Interface. Ist das korrekt? Meinem Verständnis nach sollte da doch der DRAP stehen, oder?
Wo kann ich ansetzen? Gibt es irgendwo logs die man sich anschauen kann? Ports (sollten ja alle nötigen freigegeben sein)?

Vielen Dank!

 ```
 alias: Test4
  description: ""
  trigger:
    - platform: device
      domain: homematicip_local
      device_id: <xyz12345566789>
      event_type: homematic.keypress
      address: 0021DF298FF8DE
      device_type: HmIPW-WRC6
      interface_id: RaspberryMatic-HmIP-RF
      type: press_short
      subtype: 6
  condition: []
  action:
    - type: toggle
      device_id: <xyz12345566789>
      entity_id: switch.hmipw_drs8_ug_a0f5_hmipw_drs8_ug_licht_buro_hauptlicht_ch7
      domain: switch
  mode: single
```
