### DISCUSSION TITLE
Running with docker-compose on a Raspberry Pi Zero

### DISCUSSION THREAD

**Discussion by michaelosthege** [OpenCCU/OpenCCU#2311] [🇺🇸 Q&A] [answered]
I'm new to RaspberryMatic and trying to follow [the wiki instructions to run via docker-compose](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI).

After creating a `docker-compose.yml` similar to the example, the `docker compose up -d` errored with

```
no matching manifest for linux/arm/v6 in the manifest list entries
```

The search did not find anything `arm/v6` or Raspberry Pi Zero related in this project's issues or discussions, so I'm writing this to document what appears to be a workaround that should maybe mentioned on the wiki page:

```yaml
version: "3.8"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    platform: linux/arm                              👈 this line
    ...
```

Disclaimer: At this point I don't know if this is compatible with the kernel modules that had to be installed.

Update: The container goes into endless restarts with `"rpimatic exited with code 132"`

__Does anybody have experience/insights/ideas that could be relevant to run this on a Pi Zero?__

* Raspberry Pi Zero W (v1.1)
* Raspbian 11 (bullseye), fresh install
