### DISCUSSION TITLE
über das HA Add On kein Zugriff auf Kanal 5 des HmIP-BWTH

### DISCUSSION THREAD

**Discussion by theoldphilip** [OpenCCU/OpenCCU#2320] [🇩🇪 Fragen&Antworten] [answered]
Ich würde gerne über die HomeAssistant Oberfläche auf den Kanal 5 des HmIP-BWTH zugreifen können.
Dieser Parameter wird mir im HA Webfront aber nicht angeboten.

Ich würde gerne die Thermostate umschalten, wenn die Wärmepumpe auf Kühlen wechselt. (per Automatisierung).
Was kann ich tun um den Parameter Heizen / Kühlen zu ändern ?

Gruß Philip

**Comment by Baxxy13** [comment, marked as answer]
Zunächst mal:
Wenn etwas nicht über die WebUI geht (Status und Bedienung) oder im DANN von WebUI-Programmen wählbar ist, dann geht das auch nicht "out-of-the-box" durch die genutzte Integration innerhalb von HA.

Welche Integration du nutzt wäre eine wichtige Information da es 2 verschiedene gibt.
Ist es "Homematic(IP) Local" dann kannst den den Dienst:
"Homematic(IP) Local: Put paramset" nutzen um den Modus von Kanal :5 zu ändern.
Sieht dann beispielhaft so aus:   
```yml
service: homematicip_local.put_paramset
data:
  device_id: 2c2eb9438f46256c3997e596e3d13a25
  channel: 5
  paramset_key: MASTER
  paramset:
    HEATING_COOLING: 0
```
Die Werte sind:
0 = Heizen
1 = Kühlen
2 = Heizen/Kühlen

(das Geschriebene bezieht sich auf ein WTH-2, sollte aber beim BWTH genauso sein)
