### DISCUSSION TITLE
Docker: HM-RPC online aber HM-REGA nicht erreichbar

### DISCUSSION THREAD

**Discussion by manni-2x** [OpenCCU/OpenCCU#2545] [🇩🇪 Fragen&Antworten]
Hallo,
ich hatte nach node.js Update eine nicht mehr funktionierende piVccu mit Iobroker Installation. Dies hat mich bewogen es über Docker nachzubauen. Raspimatic und Iobroker gem. Compose-Anleitung ([Installation Docker OCI](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI), Pkt. 'Using docker compose') installiert und funktionert. Die HM-RPC und HM-REGA waren aber über die ccu-IP 192.168.178.37 nicht erreichbar, daher habe ich die shim-ccu aus dem Abschnitt "Manual Installation" Pkt.8 ebenfals eingerichtet. 

```
pi@raspberrypi:~ $ cat /etc/network/if-up.d/99-ccu-shim-network
#!/bin/sh
if [ "$IFACE" = "eth0" ]; then
  if ! ip link show ccu-shim >/dev/null 2>&1; then
    ip link add ccu-shim link eth0 type macvlan mode bridge
    ip addr add 192.168.178.19 dev ccu-shim
    ip link set ccu-shim up
    ip route add 192.168.178.37 dev ccu-shim protocol static
  fi
fi
```

Die HM-RPC lief danach. Die HM-REGA bricht mit Fehler "CCU 192.168.178.19 unreachable" ab.
Den Port 1999 habe ich in sowohl in Raspimatic- als auch in Iobroker-Container durchgereicht, in Raspimatic-Firewall freigeschaltet (s.u.)

Compose.yaml des Raspimatic Container:

```
version: "3.8"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: ccu
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "80:80"
      - "1999-2001:1999-2001" # HM
      - "2010:2010"
      - "8081-8082:8081-8082"
      - "8181:8181"
      - "8284:8284"    #socketIO
      - "9292:9292"
    volumes:
      - /opt/appdata/ccu_data:/usr/local:rw
      - /lib/modules:/lib/modules:ro
      - /run/udev/control:/run/udev/control
    networks:
      ccu:
        ipv4_address: 192.168.178.37

#volumes:
#ccu_data:
networks:
  ccu:
    name: ccu
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.178.0/24
          gateway: 192.168.178.1
```

Raspimatic Container Log:

```
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 192.168.178.37, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/GPIO@fe201000.serial, HmIP: HM-MOD-RPI-PCB/GPIO@fe201000.serial, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..OK
Starting rfd: .OK
Starting HMIPServer: ..............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.73.9.20231130 (raspmatic_oci_arm)
```

lt. nmap auf Raspi-Host 192.168.178.30 ist der HM-REGA port 1999 auf 192.168.178.37 offen,
 auf 192.168.178.19 aber nicht (??):

```
pi@raspberrypi:~ $ sudo nmap -sT 192.168.178.19
Starting Nmap 7.93 ( https://nmap.org ) at 2023-12-04 13:32 GMT
Nmap scan report for shim-ccu.fritz.box (192.168.178.19)
Host is up (0.00084s latency).
Not shown: 995 closed tcp ports (conn-refused)
PORT     STATE SERVICE
22/tcp   open  ssh
53/tcp   open  domain
8090/tcp open  opsmessaging
8180/tcp open  unknown
9100/tcp open  jetdirect
Nmap done: 1 IP address (1 host up) scanned in 0.30 seconds
```

```
pi@raspberrypi:~ $ sudo nmap -sT 192.168.178.37
Starting Nmap 7.93 ( https://nmap.org ) at 2023-12-04 13:32 GMT
Nmap scan report for Homematic-CCU.fritz.box (192.168.178.37)
Host is up (0.0010s latency).
Not shown: 992 closed tcp ports (conn-refused)
PORT     STATE    SERVICE
22/tcp    filtered ssh
80/tcp    open     http
443/tcp   open     https
1999/tcp open     tcp-id-port
2000/tcp open     cisco-sccp
2001/tcp open     dc
2010/tcp open     search
8181/tcp open     intermapper
MAC Address: 02:42:C0:A8:B2:25 (Unknown)
Nmap done: 1 IP address (1 host up) scanned in 1.63 seconds
```

Die Firewall auf Homematic ist offen:
<img width="281" alt="image" src="https://github.com/jens-maus/RaspberryMatic/assets/37208979/f6bf6672-163e-40f6-a53b-a8cee08fa532">

Die laufende HM-RPC in iobroker greift auf ccu über 192.168.178.19:2001, Adapter [IPv4] 172.22.0.2 - eth0, callback 192.168.178.30 (Raspi-Host), Protokoll XML-RPC, HM-REGA ebenfalls ccu-IP 192.168.178.19

Was habe ich noch übersehen, bzw. wie bekomme ich die HM-REGA zum laufen?

Gruß
Manni

**Comment by manni-2x** [comment]
Vom Webbrowser (Edge) her scheint mir dass die shim-ccu  nicht alle ports durchlässt:
1. ccu-IP 192.168.178.37 port 1999
<img width="339" alt="image" src="https://github.com/jens-maus/RaspberryMatic/assets/37208979/8a6c1bf9-c825-49b3-9783-9dc878ab30f8">

2. shim-ccu-IP 192.168.178.19 port 1999
<img width="349" alt="image" src="https://github.com/jens-maus/RaspberryMatic/assets/37208979/6fdb55e5-6c38-4b9a-b862-de11945e668a">

Ist das die Ursache dass HM-REGA keine Verbindung zum Host 192.168.178.19:1999 findet, wie kann man das lösen?

**Reply by Marc-Berg** [reply]
Ich bin völlig blank, was das Thema Home-/Raspberrymatic angeht. Also entschuldige, wenn ich das nicht gleich auf die Reihe bekomme. Habe mir aber mal deine Konfig angeschaut. Die ".19" ist doch nur eine Hilfsadresse, um das Routing vom Host zum Macvlan zu ermöglichen. Ich verstehe noch nicht, wohin du dich eigentlich verbinden willst, also was ist das Ziel? Die ".19" kann es aus meiner Sicht nicht sein. Welche IP-Adresse hat der ioBroker?

**Reply by manni-2x** [reply]
Hallo,
danke für die Antwort. Die iobroker- Einstellungen habe ich im Satz: 
„Die laufende HM-RPC in iobroker greift auf ccu über 192.168.178.19:2001, Adapter [IPv4] 172.22.0.2 - eth0, callback 192.168.178.30 (Raspi-Host), Protokoll XML-RPC, HM-REGA ebenfalls ccu-IP 192.168.178.19“
erfasst, d.h. beide Adapter haben in iobroker die Ziel-IP 192.168.178.19 (die .37 ist vom Host nicht erreichbar). HM-RPC kann auf die .19 zugreifen (ist grün) nur der HM-REGA nicht. Für‘s letzte habe ich in Container den Port 1999 geöffnet.
Über die .37 ist die ccu Oberfläche erreichbar.

**Reply by Marc-Berg** [reply]
Super Idee, den gleichen Satz, den ich schon beim ersten Mal nicht verstanden habe, ein zweites Mal reinzukopieren. Das hilft :-)

Also nochmal andere Fragen: Gibt es eine weitere Komponente, die die IP-Adresse "192.168.178.19" hat? Welches Ziel willst du mit der ".19" erreichen, einen Container?

**Reply by manni-2x** [reply]
Sorry, habe es nicht erkannt das es unverständlich ist. Es sind die Einstellungen in HM-RPC/REGA Adapter in iobroker - war einfacher als hardcopys zu machen.
Zu .19 IP - die sollte diesen iob Adaptern einen Zugriff auf die ccu gewähren.
Lt. o.g. Anleitung gewährt die ccu-shim bridge (.19) dem Raspi-Host einen Zugriff auf den ccu-Container (.37) mit Macvlan Netzwerk. Zugleich hat der iob Container mit Bridge-Netz einen Zugriff auf Raspi-Host übers Portmapping 1999-2001:1999-2001. So sollten die iob HM Adapter mit dem ccu/Raspimatic kommunizieren können - was mit HM-RPC Adapter über den Port 2001 auch funktioniert.

Eine zusätzliche Anbindung des ccu-Containers stattdessen ans bridge-Netz des iob-Containers schien mir einfacher, funktionierte aber mit .37 IP nicht, die internen Docker IP's seien nicht fix - probiert hatte ich die auch. Es ist in diesem Fall für mich auch schwieriger die drei IP's für Iob HM-Adapter (ccu, Adapter, callback) korrekt zusammenzustellen.

**Reply by Marc-Berg** [reply]
Langsam steige ich durch (glaube ich). Da läuft einiges falsch.
1. sämtliche Portmappings für einen Container in einem MACVLAN sind komplett sinnlos. Die kannst du alle aus deiner Compose Datei entfernen. Dann wirst du feststellen, dass alles genauso gut oder schlecht läuft wie vorher. Ein Container im MACVLAN ist von allen Geräten im Heimnetz auf allen Ports erreichbar, AUSSER vom Docker Host selbst. **Nur dafür** machst du das mit dem "shim" Netzwerk Link.
2. Die IP-Adresse ".19" ist ausschließlich für den Übergang vom Host zum MACVLAN vorgesehen und wird **niemals direkt** angeprochen. Das steht auch so an keiner Stelle in der Anleitung.
3. Portmappings für den ioBroker Container im Bridge-Netzwerk sind **nur und wirklich NUR** für **eingehende** Kommunikation notwendig. Also z.B. die 8081, 8082 und was sonst noch als SERVER im Container läuft. Auf die Ports 1999-2001 wird nur von der ccu gehört, also müssen sie im iob Container nicht gemappt werden.
4. Um von einem Container in einem Bridge-Netzwerk auf einen im MACVLAN (oder umgekehrt) zugreifen zu können, solltest du den iob Container **zusätzlich** ins MACVLAN hängen. Dann musst du dich auch nicht mit IP-Adressen rumärgern, die Container sind untereinander über den Namen bzw. Hostnamen erreichbar (in deinem Fall "ccu").

**Reply by Marc-Berg** [reply]
... oder du steckst den ioBroker nur in das MACVLAN und wirfst die Bridge weg. Dann benötigst du gar keine Portmappings mehr, und beide Container können miteinander reden, bis der Arzt kommt.

Anpassungen an IP oder Volumes sind natürlich noch notwendig:

```
version: "3.8"
services:
##### CCU #####
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: ccu
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /opt/appdata/ccu_data:/usr/local:rw
      - /lib/modules:/lib/modules:ro
      - /run/udev/control:/run/udev/control
    networks:
      ccu:
        ipv4_address: 192.168.178.37
##### IOBROKER #####
  iobroker:
    container_name: iobroker
    image: buanet/iobroker:latest
    hostname: iobroker
    restart: unless-stopped
    networks:
      ccu:
        ipv4_address: 192.168.178.38
    volumes:
      - /opt/docker/iobroker:/opt/iobroker
##### NETWORKS #####
networks:
  ccu:
    name: ccu
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.178.0/24
          gateway: 192.168.178.1
```
