### DISCUSSION TITLE
Use HomeAssistant sensors inside of RasperryMatic / CCU3

### DISCUSSION THREAD

**Discussion by simllll** [OpenCCU/OpenCCU#2927] [🇺🇸 Q&A] [answered]
Hello everyone,
I've successfully set up the RaspberryMatic AddOn inside of Home Assistant. I also got the RFUSB stick working and paired the first devices. So far, so good.

But now I've hit the first problem. After installing the HmIP-FALMOT-C12 (floor heating actor), I discovered that I can't operate it without a temperature sensor. While I can briefly open the actuators, they immediately revert due to some internal routines (couldn't find out what was triggering it) and close again. (They work fine and I even can overwrite them as soon as I add a thermostat to the heating group). However, I have several temperature sensors in my apartment (e.g., from the air conditioning units or various Zigbee sensors), and I was thinking about the following scenario:

* Create a virtual thermostat in the CCU3 / RaspberryMatic (HM-IP).
* Set up a Home Assistant automation that updates the sensor whenever it changes.
* Use the "virtual device" inside of CCU3 like a real one and combine it with the relevant heating groups.

Specifically, I'd like to apply this for the opening sensors, while for temperature, I'll likely end up installing Homematic thermostats anyway.

TL;DR: How could I create a "fake" / virtual device in RaspberryMatic that I can feed with real data via Home Assistant automations, so that I can use my existing devices inside RasperryMatic?

I've already tried [Homematic Virtual Interface](https://github.com/thkl/Homematic-Virtual-Interface) and the [CuX-Daemon](https://github.com/jens-maus/cuxd), but without success. With the HVI, I can only use plugins, but I'm unable to create a custom/virtual device. The CuX Daemon sounded promising, but unfortunately, there are no HM-IP devices. I can only create "HM" devices, which I can't combine with my HM-IP devices, e.g., in groups.

Thanks for any input! 💯

Simon

// This is the Englisch version, German version is here: https://github.com/jens-maus/RaspberryMatic/discussions/2926

**Comment by jens-maus** [comment, marked as answer]
> But now I've hit the first problem. After installing the HmIP-FALMOT-C12 (floor heating actor), I discovered that I can't operate it without a temperature sensor. While I can briefly open the actuators, they immediately revert due to some internal routines (couldn't find out what was triggering it) and close again. (They work fine and I even can overwrite them as soon as I add a thermostat to the heating group). However, I have several temperature sensors in my apartment (e.g., from the air conditioning units or various Zigbee sensors), and I was thinking about the following scenario:
> 
> * Create a virtual thermostat in the CCU3 / RaspberryMatic (HM-IP).
> * Set up a Home Assistant automation that updates the sensor whenever it changes.
> * Use the "virtual device" inside of CCU3 like a real one and combine it with the relevant heating groups.
> 
> Specifically, I'd like to apply this for the opening sensors, while for temperature, I'll likely end up installing Homematic thermostats anyway.

Unfortunately, non of your ideas/suggestions will work. The HmIP-FALMOT and all other Homematic Floor actuators **require** a coupled wall thermostat. There is no possibility to create a virtual thermostat, automation or anything like that to manually "drive" these type of floor heating actuators. They can only operate with a coupled wall thermostat from HomematicIP because they can only perform their internal and automated operations together with their wall thermostats. Furthermore, there is no possibility to explicitly open or close one channel / motor of these floor actuators because all this is done solely via internal logic between the floor actuator and the wall thermostat. All you can do is to set a certain target temperature at the wall thermostat and then the thermostat and the floor actor will perform their internal logic until this temperature is reached.

**Reply by simllll** [reply]
Thanks for your response, the CuX-Daemon can create HM devices, but not HM-IP devices... as your are the author, you also think there is no way to actually add this kind of feature?

Regarding window openings, I found a blueprint (https://community.home-assistant.io/t/homematic-ip-local-reduce-room-temperature-when-a-window-or-door-is-opened/373305) and adapted it a bit:
<details>

<summary>
On Window/Door Openings notify rasperryamatic.
</summary>

blueprints/automation/ccu3/doorsensors.yaml

```yaml
blueprint:
  name: Window Open, Notify HomeMatic CCU
  description: >
    An automation blueprint that reduces the set temperature of your climate
    device or group if a window sensor is open for more than the preset wait time.
    It uses the Homematic window sensor channel to set the temperature to the "Open-window
    temperature" set in the device configuration. You should set the "Mode for temperature
    fall detection" to Inactive to avoid conflicts. It waits until the window is closed
    again in order to restore the climate entity temperature. It has an optional blocking
    entity to prevent the automation running unnecessarily, for example during the
    Summer season.
  domain: automation
  input:
    window_entity:
      name: Window Sensor
      description: The window or door sensor that will control the climate entity.
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class:
                - window
                - door
          multiple: true
    open_delay:
      name: Windows Open Wait Time
      description: Time to delay after window opens before notifying HomeMatic.
      default: 30
      selector:
        number:
          min: 0.0
          max: 600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    blocking_entity:
      name: (OPTIONAL) Blocking Entity
      description: >
        If this entity's state is on, it will prevent the automation from
        running. E.g. summer mode or away mode.
      default:
      selector:
        entity:
          filter:
            domain: input_boolean
    climate_entity:
      name: Climate Device
      description: The climate entity that is controlled by the window sensor.
      selector:
        device:
          entity:
            - integration: homematicip_local
  source_url: https://community.home-assistant.io/t/homematic-ip-local-reduce-room-temperature-when-a-window-or-door-is-opened/373305
variables:
  blocking_entity: !input "blocking_entity"
  climate_target: !input "climate_entity"
  climate_id: !input "climate_entity"
  open_delay: !input "open_delay"
  windows: !input "window_entity"
trigger:
  - trigger: state
    entity_id: !input "window_entity"
    to: "on"
    for: !input "open_delay"
condition:
  - condition: template
    value_template: "{{ (blocking_entity == none) or (states[blocking_entity].state == 'off') }}"
action:
  - action: homematicip_local.set_device_value
    data:
      device_id: "{{ climate_id }}"
      channel: 1
      parameter: WINDOW_STATE
      value: 1
  - wait_template: >
      {% set closed = namespace(bool=true) %}
      {% for state in states.binary_sensor%}
          {% if state.entity_id in windows %}
              {% if state.state == "on" %}
               {% set closed.bool = false %}
              {% endif %}
         {% endif %}
      {% endfor %}
      {{closed.bool}}
    continue_on_timeout: false
  - action: homematicip_local.set_device_value
    data:
      device_id: "{{ climate_id }}"
      channel: 1
      parameter: WINDOW_STATE
      value: 0
mode: restart
max_exceeded: silent

```
</details>
It's not perfect, but it works ;-)
